# Site Configuration.
name: 'My Jekyll Site'
description: 'A basic templated jekyll site.'

# Meta.
micro_format: 'http://schema.org/' # Link to the schema.org microformat for the site.

# SEO.
analytics:
  tracking_code: 'UA-000000-00'
  domain: 'www.example.com'

# Contact details.
contact:
  email: 'info@example.com'
  phone: 
    link: '+44000000000'
    display: '+44 (0) 000 - 00000'
  address:
    street: 'PO Box 1'
    town: 'Fake Town'
    county: 'Fakington'
    country: 'United Fakedom'
    post_code: 'FAK3 0NE'

# Asset Pipeline Configuraiton.
assets:
  js_compressor:  uglifier
  css_compressor: sass

  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images